name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup python
      uses: actions/setup-python@v1

    - name: Install pipenv
      run: sudo -H pip install -U pipenv

    - name: Build
      run: pipenv install && pipenv run python -m __init__

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: / # The folder the action should deploy.
