name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup python
      uses: actions/setup-python@v1

    - name: Setup pipenv
      run: |
        sudo -H pip install -U pipenv
        pipenv install
        mkdir build
        cp -r static build

    - name: Build (osgameclones.games)
      run: |
        wget https://raw.githubusercontent.com/opengaming/osgameclones/master/schema/games.yaml
        pipenv run python -m pykwalify-webform games.yaml build/osgameclones/game.html

    - name: Build (osgameclones.originals)
      run: |
        wget https://raw.githubusercontent.com/opengaming/osgameclones/master/schema/originals.yaml
        pipenv run python -m pykwalify-webform originals.yaml build/osgameclones/original.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
