name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup python
      uses: actions/setup-python@v1

    - name: Setup pipenv
      run: |
        sudo -H pip install -U pipenv
        pipenv install
        mkdir build
        cp -r static build

    - name: Build (osgameclones.games)
      run: |
        wget https://raw.githubusercontent.com/opengaming/osgameclones/master/schema/games.yaml
        pipenv run python -m __init__ games.yaml build/osgameclones/game.html game

    - name: Build (osgameclones.originals)
      run: |
        wget https://raw.githubusercontent.com/opengaming/osgameclones/master/schema/originals.yaml
        pipenv run python -m __init__ originals.yaml build/osgameclones/original.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
