permissions:
  actions: write
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Setup pipenv
      run: |
        sudo -H pip install -U pipenv
        pipenv install
        mkdir build

    - name: Build (osgameclones.games)
      run: |
        wget https://raw.githubusercontent.com/opengaming/osgameclones/master/schema/games.yaml
        pipenv run python -m pykwalify_webform games.yaml build/osgameclones/game.html build/ "" --name="Add game" --base_url=/pykwalify-webform

    - name: Build (osgameclones.originals)
      run: |
        wget https://raw.githubusercontent.com/opengaming/osgameclones/master/schema/originals.yaml
        pipenv run python -m pykwalify_webform originals.yaml build/osgameclones/original.html build/ "" --name="Add original game" --base_url=/pykwalify-webform

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
